---

- block:

    - name: (CentOS/RedHat) Add MongoDB repository
      yum_repository:
        name: 'mongodb-org-{{ mongodb_version }}'
        description: MongoDB Repository
        baseurl: 'https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/'
        gpgcheck: true
        enabled: true
        gpgkey: 'https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc'

    - name: (CentOS/RedHat) Install MongoDB
      yum:
        name: mongodb-org
        state: present

  when: ansible_os_family == 'RedHat'
