---

- name: Create MongoDB root user siteRootAdmin
  mongodb_user:
    login_port: '{{ mongodb_listen_port }}'
    database: admin
    name: '{{ mongodb_admin_user }}'
    password: '{{ mongodb_admin_password }}'
    roles: root
  no_log: true
  changed_when: false

- name: Create MongoDB administrative user siteUserAdmin
  mongodb_user:
    login_user: '{{ mongodb_admin_user }}'
    login_password: '{{ mongodb_admin_password }}'
    login_port: '{{ mongodb_listen_port }}'
    database: '{{ item.database }}'
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    roles: '{{ item.roles | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ mongodb_users }}'
  when: mongodb_users is defined and mongodb_users|length
  no_log: true
  changed_when: false
