---
- name: Converge
  hosts: all

  vars:

    mongodb_users:
      - name: tryit
        database: tryit
        password: tryitpassword
        roles: readWrite

  roles:
    - role: cloudweeb.mongodb
